#!/bin/sh
ENVIRONMENTD="$HOME/.config/environment.d"
I3ENVD="$HOME/.config/i3/environment.d"

set -a
if [ -d "$ENVIRONMENTD" ]; then
	for conf in $(ls "$ENVIRONMENTD"/*.conf)
	do
		. "$conf"
	done

fi
if [ -d "$I3ENVD" ]; then
	for conf in $(ls "$I3ENVD"/*.conf)
	do
		. "$conf"
	done
fi
unset conf
set +a
cat "$I3ENVD/*.conf" | xargs systemctl --user set-environment
exec i3 "$@"
